
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: localhost:5000/final-project_backend
    ports:
      - "3402:3402"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: localhost:5000/final-project_frontend
    ports:
      - "8777:8777"
    networks:
      - app-network

  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry

networks:
  app-network:
    driver: bridge

volumes:
  registry-data:
